import pandas as pd

from src.transformation.bfi import (
    build_ancien_mapping_type_ressource_emploi,
    build_taux_change_bbe_bam,
    build_taux_change_virement_bam,
    calculate_objectives_per_fdc,
)
from tests.conftest import compare_dataframes


def test_calculate_objectives_per_family(spark):
    df = spark.createDataFrame(
        [
            (
                "2024-10-18",
                "001A",
                "Autres",
                "No",
                None,
                None,
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-09-17",
                "002A",
                "Crédit court terme",
                "Yes",
                "1",
                None,
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-10-18",
                "003A",
                "Crédit court terme",
                "Yes",
                "1",
                None,
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-09-17",
                "004A",
                "Crédit moyen long terme",
                "Yes",
                None,
                "2",
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-10-18",
                "005A",
                "Crédit moyen long terme",
                "Yes",
                None,
                "2",
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-09-17",
                "006A",
                "Ressources à vue",
                "Yes",
                None,
                None,
                "3",
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-10-18",
                "007A",
                "Ressources à vue",
                "Yes",
                None,
                None,
                "3",
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-09-17",
                "008A",
                "Dépôts à terme",
                "Yes",
                None,
                None,
                None,
                "4",
                None,
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-10-18",
                "009A",
                "Dépôts à terme",
                "Yes",
                None,
                None,
                None,
                "4",
                None,
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-09-17",
                "010A",
                "Société de financement",
                "PRET_EC",
                None,
                None,
                None,
                None,
                "5",
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-10-18",
                "011A",
                "Société de financement",
                "PRET_EC",
                None,
                None,
                None,
                None,
                "5",
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-09-17",
                "012A",
                "Société de financement",
                "DEC_EC",
                None,
                None,
                None,
                None,
                "6",
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-10-18",
                "013A",
                "Société de financement",
                "DEC_EC",
                None,
                None,
                None,
                None,
                "6",
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-09-17",
                "014A",
                "Société de financement",
                "SF",
                None,
                None,
                None,
                None,
                "7",
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-10-18",
                "015A",
                "Société de financement",
                "SF",
                None,
                None,
                None,
                None,
                "7",
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-09-17",
                "016A",
                "Société de financement",
                "No",
                None,
                None,
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-10-18",
                "017A",
                "Société de financement",
                "No",
                None,
                None,
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
            ),
            (
                "2024-10-17",
                "018A",
                "Autres",
                "No",
                None,
                None,
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
            ),
        ],
        [
            "dttrtm",
            "cdgest_ctx",
            "famille_tdb_banque",
            "type_ressource_emploi",
            "objectif_cct",
            "objectif_cmt",
            "objectif_rav",
            "objectif_rat",
            "objectif_sf",
            "last_month_soldejourdb_devise",
            "last_month_soldejourcr_devise",
            "last_year_soldejourdb_devise",
            "last_year_soldejourcr_devise",
        ],
    )

    actual = calculate_objectives_per_fdc(df, partition_date="2024-10-18")

    expected = pd.DataFrame(
        [
            (
                "2024-10-18",
                "001A",
                "Autres",
                "No",
                None,
                None,
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
                False,
                None,
                None,
                None,
                None,
                None,
                None,
                9,
            ),
            (
                "2024-09-17",
                "002A",
                "Crédit court terme",
                "Yes",
                1000000.0,
                None,
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
                True,
                20.0,
                10.0,
                30.0,
                40.0,
                999970.0,
                None,
                9,
            ),
            (
                "2024-10-18",
                "003A",
                "Crédit court terme",
                "Yes",
                1000000.0,
                None,
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
                True,
                20.0,
                10.0,
                30.0,
                40.0,
                999970.0,
                None,
                9,
            ),
            (
                "2024-09-17",
                "004A",
                "Crédit moyen long terme",
                "Yes",
                None,
                2000000.0,
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
                True,
                20.0,
                10.0,
                30.0,
                40.0,
                1999970.0,
                None,
                9,
            ),
            (
                "2024-10-18",
                "005A",
                "Crédit moyen long terme",
                "Yes",
                None,
                2000000.0,
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
                True,
                20.0,
                10.0,
                30.0,
                40.0,
                1999970.0,
                None,
                9,
            ),
            (
                "2024-09-17",
                "006A",
                "Ressources à vue",
                "Yes",
                None,
                None,
                3000000.0,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
                True,
                20.0,
                10.0,
                30.0,
                40.0,
                None,
                2999960.0,
                9,
            ),
            (
                "2024-10-18",
                "007A",
                "Ressources à vue",
                "Yes",
                None,
                None,
                3000000.0,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
                True,
                20.0,
                10.0,
                30.0,
                40.0,
                None,
                2999960.0,
                9,
            ),
            (
                "2024-09-17",
                "008A",
                "Dépôts à terme",
                "Yes",
                None,
                None,
                None,
                4000000.0,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
                True,
                20.0,
                10.0,
                30.0,
                40.0,
                None,
                3999960.0,
                9,
            ),
            (
                "2024-10-18",
                "009A",
                "Dépôts à terme",
                "Yes",
                None,
                None,
                None,
                4000000.0,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
                True,
                20.0,
                10.0,
                30.0,
                40.0,
                None,
                3999960.0,
                9,
            ),
            (
                "2024-09-17",
                "010A",
                "Société de financement",
                "PRET_EC",
                None,
                None,
                None,
                None,
                5000000.0,
                20.0,
                10.0,
                30.0,
                40.0,
                True,
                20.0,
                10.0,
                30.0,
                40.0,
                4999970.0,
                None,
                9,
            ),
            (
                "2024-10-18",
                "011A",
                "Société de financement",
                "PRET_EC",
                None,
                None,
                None,
                None,
                5000000.0,
                20.0,
                10.0,
                30.0,
                40.0,
                True,
                20.0,
                10.0,
                30.0,
                40.0,
                4999970.0,
                None,
                9,
            ),
            (
                "2024-09-17",
                "012A",
                "Société de financement",
                "DEC_EC",
                None,
                None,
                None,
                None,
                6000000.0,
                20.0,
                10.0,
                30.0,
                40.0,
                True,
                20.0,
                10.0,
                30.0,
                40.0,
                5999970.0,
                None,
                9,
            ),
            (
                "2024-10-18",
                "013A",
                "Société de financement",
                "DEC_EC",
                None,
                None,
                None,
                None,
                6000000.0,
                20.0,
                10.0,
                30.0,
                40.0,
                True,
                20.0,
                10.0,
                30.0,
                40.0,
                5999970.0,
                None,
                9,
            ),
            (
                "2024-09-17",
                "014A",
                "Société de financement",
                "SF",
                None,
                None,
                None,
                None,
                7000000.0,
                20.0,
                10.0,
                30.0,
                40.0,
                True,
                20.0,
                10.0,
                30.0,
                40.0,
                6999970.0,
                None,
                9,
            ),
            (
                "2024-10-18",
                "015A",
                "Société de financement",
                "SF",
                None,
                None,
                None,
                None,
                7000000.0,
                20.0,
                10.0,
                30.0,
                40.0,
                True,
                20.0,
                10.0,
                30.0,
                40.0,
                6999970.0,
                None,
                9,
            ),
            (
                "2024-09-17",
                "016A",
                "Société de financement",
                "No",
                None,
                None,
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
                False,
                None,
                None,
                None,
                None,
                None,
                None,
                9,
            ),
            (
                "2024-10-18",
                "017A",
                "Société de financement",
                "No",
                None,
                None,
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
                False,
                None,
                None,
                None,
                None,
                None,
                None,
                9,
            ),
            (
                "2024-10-17",
                "018A",
                "Autres",
                "No",
                None,
                None,
                None,
                None,
                None,
                20.0,
                10.0,
                30.0,
                40.0,
                False,
                None,
                None,
                None,
                None,
                None,
                None,
                9,
            ),
        ],
        columns=[
            "dttrtm",
            "cdgest_ctx",
            "famille_tdb_banque",
            "type_ressource_emploi",
            "objectif_cct",
            "objectif_cmt",
            "objectif_rav",
            "objectif_rat",
            "objectif_sf",
            "last_month_soldejourdb_devise",
            "last_month_soldejourcr_devise",
            "last_year_soldejourdb_devise",
            "last_year_soldejourcr_devise",
            "is_tro",
            "last_month_soldejourdb_devise_per_fdc",
            "last_month_soldejourcr_devise_per_fdc",
            "last_year_soldejourdb_devise_per_fdc",
            "last_year_soldejourcr_devise_per_fdc",
            "delta_year_db",
            "delta_year_cr",
            "previous_month",
        ],
    )

    compare_dataframes(
        actual,
        expected,
        sort_by=[
            "cdgest_ctx",
        ],
    )


def test_build_ancien_mapping_type_ressource_emploi(spark):
    df = spark.createDataFrame(
        [
            ("50", "50", "10", "a"),
            ("5", "5", "10", "a"),
            ("51", "51", "10", "a"),
            ("5", "5", "10", "a"),
            (None, None, "10", "a"),
            ("11", "11", "10", "a"),
        ],
        ["ligne_credit", "ligne_debit", "pci", "nature"],
    )

    actual = build_ancien_mapping_type_ressource_emploi(df)

    expected = pd.DataFrame(
        [
            ("50", "100000", "a", "RESS", "R.BAM/TRES/CCP"),
            ("50", "100000", "a", "EMP", "R.BAM/TRES/CCP"),
            ("5", "100000", "a", "RESS", "AUTRES"),
            ("5", "100000", "a", "EMP", "AUTRES"),
            ("51", "100000", "a", "RESS", "DET/EC"),
            ("51", "100000", "a", "EMP", "DET/EC"),
            ("11", "100000", "a", "RESS", "CAV/EC"),
            ("11", "100000", "a", "EMP", "CAV/EC"),
        ],
        columns=["CODE_LIGNE", "PCI", "NATURE", "CATEGORIE", "Type_RESS_EMPO"],
    )

    compare_dataframes(
        actual,
        expected,
        sort_by=["CODE_LIGNE", "PCI", "NATURE", "CATEGORIE", "Type_RESS_EMPO"],
    )


def test_build_taux_change_bbe_bam(spark):
    df = spark.createDataFrame(
        [
            (120, 120, 10, "A", "2024-01-01", "2024-01-01"),
            (100, 100, 10, "A", "2024-01-01", "2024-01-01"),
            (120, 120, 10, "A", "2024-01-01", "2024-01-01"),
            (100, 100, 10, "A", "2024-01-01", "2024-01-01"),
            (120, 120, 10, "A", "2024-01-01", "2024-01-01"),
        ],
        [
            "venteClientele",
            "achatClientele",
            "uniteDevise",
            "libDevise",
            "date",
            "partitiondate",
        ],
    )

    actual = build_taux_change_bbe_bam(df)

    expected = pd.DataFrame(
        [
            (120, 120, 10, "A", "2024-01-01", "2024-01-01", 18),
            (100, 100, 10, "A", "2024-01-01", "2024-01-01", 15),
            (120, 120, 10, "A", "2024-01-01", "2024-01-01", 18),
            (100, 100, 10, "A", "2024-01-01", "2024-01-01", 15),
            (120, 120, 10, "A", "2024-01-01", "2024-01-01", 18),
        ],
        columns=[
            "venteClientele",
            "achatClientele",
            "uniteDevise",
            "libDevise",
            "date",
            "partitiondate",
            "moyen_par_unite",
        ],
    )

    compare_dataframes(actual, expected, sort_by=["venteClientele"])


def test_build_taux_change_virement_bam(spark):
    df = spark.createDataFrame(
        [
            (100, 5, "A", "2024-01-01", "2024-01-01"),
            (120, 8, "A", "2024-01-01", "2024-01-01"),
            (140, 7, "A", "2024-01-01", "2024-01-01"),
            (100, 5, "A", "2024-01-01", "2024-01-01"),
            (180, 10, "A", "2024-01-01", "2024-01-01"),
        ],
        ["moyen", "uniteDevise", "libDevise", "date", "partitiondate"],
    )

    actual = build_taux_change_virement_bam(df)

    expected = pd.DataFrame(
        [
            (100, 5, "A", "2024-01-01", "2024-01-01", 20),
            (120, 8, "A", "2024-01-01", "2024-01-01", 15),
            (140, 7, "A", "2024-01-01", "2024-01-01", 20),
            (100, 5, "A", "2024-01-01", "2024-01-01", 20),
            (180, 10, "A", "2024-01-01", "2024-01-01", 18),
        ],
        columns=[
            "moyen",
            "uniteDevise",
            "libDevise",
            "date",
            "partitiondate",
            "moyen_par_unite",
        ],
    )

    compare_dataframes(actual, expected, sort_by=["moyen"])
