repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: pretty-format-json
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix, --config=pyproject.toml]
      - id: ruff-format
        args: [--config=pyproject.toml, --verbose]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
    - id: mypy
      args: [
              --config=pyproject.toml,
              --explicit-package-bases,
              --namespace-packages,
              --check-untyped-defs,
              --ignore-missing-imports
            ]
