from pyspark.sql import DataFrame
from pyspark.sql.functions import (
    col,
    lit,
    split,
    substring,
    to_date,
    trim,
)


def build_rma_watanya(df: DataFrame, partition_date: str) -> DataFrame:
    return (
        df.withColumn("ENTREPRISE", lit("RMA WATANYA"))
        .withColumn("TYPE_CONTRAT", trim(substring(df.value, 1, 1)))
        .withColumn("NUMERO_CONTRAT", trim(substring(df.value, 2, 14)))
        .withColumn("NUMERO_COMPTE", trim(substring(df.value, 16, 24)))
        .withColumn("VENDEUR", trim(substring(df.value, 40, 5)))
        .withColumn("DATE_EFFET", trim(substring(df.value, 45, 8)))
        .withColumn("TAUX_FRAIS_GESTION", trim(substring(df.value, 53, 5)))
        .withColumn("DATE_PREMIERE_COTISATION", trim(substring(df.value, 58, 8)))
        .withColumn("DATE_TERME", trim(substring(df.value, 66, 8)))
        .withColumn("DATE_VERSEMENT_INITIAL", trim(substring(df.value, 74, 8)))
        .withColumn("MONTANT_VERSEMENT_INITIAL", trim(substring(df.value, 82, 15)))
        .withColumn("PROFESSION", trim(substring(df.value, 97, 30)))
        .withColumn("ACTIVITE", trim(substring(df.value, 127, 40)))
        .withColumn("MONTANT_PRIME_RMA", trim(substring(df.value, 167, 15)))
        .withColumn("MONTANT_COMMISSION_GESTION", trim(substring(df.value, 182, 15)))
        .withColumn(
            "MONTANT_COMMISSION_PRODUCTIVITE", trim(substring(df.value, 197, 15))
        )
        .withColumn("MONTANT_TVA", trim(substring(df.value, 212, 15)))
        .withColumn("CODE_RACHAT", trim(substring(df.value, 227, 1)))
        .withColumn("CODE_DECLARATION_SINISTRE", trim(substring(df.value, 228, 1)))
        .withColumn("CODE_SUSPENSION", trim(substring(df.value, 229, 1)))
        .withColumn("DATE_SUSPENSION", trim(substring(df.value, 230, 8)))
        .withColumn("DATE_REPRISE", trim(substring(df.value, 238, 8)))
        .withColumn("DATE_DERNIER_PREVELEMENT", trim(substring(df.value, 246, 8)))
        .withColumn(
            "MONTANT_VERSEMENT_EXCEPTIONNEL", trim(substring(df.value, 254, 15))
        )
        .withColumn("DATE_VERSEMENT_EXCEPTIONNEL", trim(substring(df.value, 269, 8)))
        .withColumn("DATE_RACHAT", trim(substring(df.value, 277, 8)))
        .withColumn("DATE_RESILIATION", trim(substring(df.value, 285, 8)))
        .withColumn("DATE_SOUSCRIPTION", trim(substring(df.value, 293, 8)))
        .withColumn("DATE_DECLARATION_SINISTRE", trim(substring(df.value, 301, 8)))
        .withColumn("DATE_REGLEMENT", trim(substring(df.value, 309, 8)))
        .withColumn("MONTANT_TOTAL_REGLEMENT", trim(substring(df.value, 317, 15)))
        .withColumn("CATEGORIE", trim(substring(df.value, 332, 50)))
        .withColumn("CHIFFRE_AFFAIRE", trim(substring(df.value, 382, 14)))
        .withColumn("ENCOURS", trim(substring(df.value, 396, 14)))
        .drop("value")
        .replace("", None)
        .na.drop("all")
        .drop_duplicates()
        .withColumn("DATE_TRAITEMENT", to_date(lit(partition_date)))
        .withColumn("partitiondate", col("DATE_TRAITEMENT"))
    )


def build_wafa_assurance(df: DataFrame, partition_date: str) -> DataFrame:
    return (
        df.withColumn("ENTREPRISE", lit("WAFA ASSURANCE"))
        .withColumn("TYPE_D", trim(substring(df.value, 1, 1)))
        .withColumn("CODE_PRODUIT", trim(substring(df.value, 2, 7)))
        .withColumn("NUMERO_CONTRAT", trim(substring(df.value, 9, 7)))
        .withColumn("NUMERO_ADHESION", trim(substring(df.value, 16, 7)))
        .withColumn("NOM", trim(substring(df.value, 23, 40)))
        .withColumn("EPARGNE", trim(substring(df.value, 63, 12)))
        .withColumn("DATE_CALCULEE", trim(substring(df.value, 75, 8)))
        .withColumn("SOLDE_AVANCE", trim(substring(df.value, 83, 12)))
        .withColumn("NANTISSEMENT", trim(substring(df.value, 95, 1)))
        .withColumn("FILLER", trim(substring(df.value, 96, 5)))
        .drop("value")
        .replace("", None)
        .na.drop("all")
        .drop_duplicates()
        .withColumn("DATE_TRAITEMENT", to_date(lit(partition_date)))
        .withColumn("partitiondate", col("DATE_TRAITEMENT"))
    )


def build_axa_assurance(df: DataFrame, partition_date: str) -> DataFrame:
    return (
        df.withColumn("ENTREPRISE", lit("AXA ASSURANCE"))
        .withColumn("PRODUIT", split(df.value, ",").getItem(0))
        .withColumn("Field2", split(df.value, ",").getItem(1))
        .withColumn("ENCOURS", split(df.value, ",").getItem(2))
        .withColumn("DATE", split(df.value, ",").getItem(3))
        .drop("value")
        .replace("", None)
        .na.drop("all")
        .drop_duplicates()
        .withColumn("DATE_TRAITEMENT", to_date(lit(partition_date)))
        .withColumn("partitiondate", col("DATE_TRAITEMENT"))
    )


def build_saham_assurance(df: DataFrame, partition_date: str) -> DataFrame:
    return (
        df.withColumn("ENTREPRISE", lit("SAHAM ASSURANCE"))
        .withColumn("TYPE_CONTRAT", trim(substring(df.value, 1, 15)))
        .withColumn("CONTRAT", trim(substring(df.value, 16, 20)))
        .withColumn("COMPTE", trim(substring(df.value, 36, 30)))
        .withColumn("VENDEUR", trim(substring(df.value, 66, 5)))
        .withColumn("DATE_EFFET", trim(substring(df.value, 71, 8)))
        .withColumn("T_FRAIS_GESTION", trim(substring(df.value, 79, 5)))
        .withColumn("DATE_PRELEVEMENT", trim(substring(df.value, 84, 8)))
        .withColumn("DATE_TERME", trim(substring(df.value, 92, 8)))
        .withColumn("DATE_PREMIER_VERSEMENT", trim(substring(df.value, 100, 8)))
        .withColumn("DATE_VERSEMENT_EXCEPTIONNEL", trim(substring(df.value, 108, 8)))
        .withColumn("MONTANT_VERSEMENT_INITIAL", trim(substring(df.value, 116, 20)))
        .withColumn("PROF", trim(substring(df.value, 136, 20)))
        .withColumn("ACTIVITE", trim(substring(df.value, 156, 20)))
        .withColumn("MONTANT_PRIME", trim(substring(df.value, 176, 20)))
        .withColumn("MONTANT_PRIME_GESTION", trim(substring(df.value, 196, 20)))
        .withColumn("MONTANT_PRIME_PROD", trim(substring(df.value, 216, 20)))
        .withColumn("MONTANT_TVA", trim(substring(df.value, 236, 10)))
        .withColumn("CODE_RACHAT", trim(substring(df.value, 246, 10)))
        .withColumn("CODE_REGEL_RACHAT", trim(substring(df.value, 256, 10)))
        .withColumn("CODE_SUSPEN", trim(substring(df.value, 266, 10)))
        .withColumn("DATE_DEBUT_SUSPEN", trim(substring(df.value, 276, 8)))
        .withColumn("DATE_FIN_SUSPEN", trim(substring(df.value, 284, 8)))
        .withColumn("DATE_DERNIER_PREVELEMENT", trim(substring(df.value, 292, 8)))
        .withColumn("MONTANT_VERS_COMPL", trim(substring(df.value, 300, 20)))
        .withColumn("DATE_VERS_COMPL", trim(substring(df.value, 320, 8)))
        .withColumn("DATE_RACHAT", trim(substring(df.value, 328, 8)))
        .withColumn("DATE_DEM_AV", trim(substring(df.value, 336, 8)))
        .withColumn("DATE_REMB_AV", trim(substring(df.value, 344, 8)))
        .withColumn("DATE_SOUSCRIPTION", trim(substring(df.value, 352, 8)))
        .withColumn("ENCOURS_NET", trim(substring(df.value, 360, 20)))
        .withColumn("ENCOURS_BRUT", trim(substring(df.value, 380, 20)))
        .drop("value")
        .replace("", None)
        .na.drop("all")
        .drop_duplicates()
        .withColumn("DATE_TRAITEMENT", to_date(lit(partition_date)))
        .withColumn("partitiondate", col("DATE_TRAITEMENT"))
    )
