events_mapping = {
    "AJOUTER_BENEFICIAIRE": "1",
    "EFFECTUER_VIREMENT": "2",
    "MAJ_INTERVENANT": "3",
    # "SUPPRIME_BENEFICIAIRE": "4",
    "MISE_A_DISPOSITION": "5",
    "ACTIVATION_ATTIJARI_SECURITE": "6",
    "DESACTIVATION_ATTIJARI_SECURITE": "7",
    "LOGIN": "8",
    "RESET_PASSWORD_TOKEN_SENT_SUCCESS": "9",
    "EFFECTUER_PAIEMENT": "A",
    "EFFECTUER_CASH_EXPRESS": "B",
    "CASH_EXPRESS_CREATE_BENEFICIARY": "C",
}
